#pragma once

#include "algorithms/graphs/dominator_tree.hpp"
#include "algorithms/graphs/graph.hpp"

#include <cstddef>
#include <vector>

namespace algorithms::graphs {

// Immutable dominance-frontier index over the subgraph reachable from `start`.
//
// For reachable vertices x and y:
//   y is in DF(x) iff x dominates at least one reachable predecessor of y and
//   x does not strictly dominate y.
//
// This direct first-principles implementation evaluates the defining predicate
// using the sealed DominatorTree index. It intentionally claims the conservative
// O(V(V+E)) construction bound of this definition-based baseline and O(V^2) worst-
// case resident frontier payload. The implementation does not claim the tighter
// complexity of optimized local/up dominance-frontier algorithms.
class DominanceFrontierIndex {
 public:
  DominanceFrontierIndex(const Graph& graph, Vertex start);

  [[nodiscard]] std::size_t vertex_count() const noexcept;
  [[nodiscard]] Vertex start() const noexcept;
  [[nodiscard]] bool reachable(Vertex vertex) const;

  // Unreachable vertices have an empty frontier. Invalid vertices throw.
  [[nodiscard]] const std::vector<Vertex>& frontier(Vertex vertex) const;
  [[nodiscard]] const std::vector<std::vector<Vertex>>& frontiers() const noexcept;

  // Returns the least deterministic closure generated by repeatedly adding the
  // frontier of definition blocks and newly discovered non-definition blocks.
  // Definition blocks must be valid and start-reachable. The returned vector is
  // sorted by vertex id and may contain an original definition when a loop puts
  // that block in its own iterated dominance frontier.
  [[nodiscard]] std::vector<Vertex> iterated_frontier(
      const std::vector<Vertex>& definitions) const;

 private:
  void validate_vertex(Vertex vertex) const;

  std::size_t vertex_count_;
  Vertex start_;
  std::vector<unsigned char> reachable_;
  std::vector<std::vector<Vertex>> frontier_;
};

}  // namespace algorithms::graphs
