#pragma once

#include "algorithms/number_theory/modular.hpp"

#include <cstddef>
#include <cstdint>
#include <limits>
#include <map>
#include <optional>
#include <stdexcept>

namespace algorithms::number_theory {
namespace detail {

inline bool discrete_log_square_at_least(std::uint64_t candidate,
                                         std::uint64_t value) {
  if (candidate == 0U) {
    return value == 0U;
  }
  const std::uint64_t quotient = value / candidate;
  if (candidate > quotient) {
    return true;
  }
  return candidate == quotient && value % candidate == 0U;
}

inline std::uint64_t discrete_log_ceil_sqrt(std::uint64_t value) {
  if (value <= 1U) {
    return value;
  }
  std::uint64_t low = 1U;
  std::uint64_t high = std::uint64_t{1} << 32U;
  while (low < high) {
    const std::uint64_t middle = low + (high - low) / 2U;
    if (discrete_log_square_at_least(middle, value)) {
      high = middle;
    } else {
      low = middle + 1U;
    }
  }
  return low;
}

}  // namespace detail

inline constexpr std::size_t kDefaultDiscreteLogBabyStepBudget = 1'000'000U;

// Returns the least non-negative exponent x < prime_modulus - 1 such that
// base^x == target (mod prime_modulus), or std::nullopt when target is not in
// the subgroup generated by base.
//
// The public contract is the multiplicative group F_p^*: prime_modulus must be
// prime and both base and target must be non-zero modulo prime_modulus.
// max_baby_steps bounds resident search memory explicitly; if ceil(sqrt(p-1))
// exceeds the supplied budget, std::length_error is thrown before allocation.
//
// Deterministic std::map storage gives O(sqrt(p) log p) worst-case time and
// O(sqrt(p)) storage within the configured budget.
[[nodiscard]] inline std::optional<std::uint64_t>
baby_step_giant_step_discrete_log(
    std::uint64_t base, std::uint64_t target, std::uint64_t prime_modulus,
    std::size_t max_baby_steps = kDefaultDiscreteLogBabyStepBudget) {
  if (!is_prime(prime_modulus)) {
    throw std::invalid_argument("discrete-log modulus must be prime");
  }
  if (max_baby_steps == 0U) {
    throw std::invalid_argument("discrete-log baby-step budget must be positive");
  }

  base %= prime_modulus;
  target %= prime_modulus;
  if (base == 0U || target == 0U) {
    throw std::invalid_argument(
        "discrete-log base and target must lie in the multiplicative group");
  }

  const std::uint64_t group_size = prime_modulus - 1U;
  const std::uint64_t step_count = detail::discrete_log_ceil_sqrt(group_size);
  if (step_count > static_cast<std::uint64_t>(max_baby_steps)) {
    throw std::length_error("discrete-log baby-step budget exceeded");
  }
  if (step_count >
      static_cast<std::uint64_t>(std::numeric_limits<std::size_t>::max())) {
    throw std::length_error("discrete-log baby-step table is too large");
  }

  std::map<std::uint64_t, std::uint64_t> baby_steps;
  std::uint64_t value = 1U;
  for (std::uint64_t exponent = 0U; exponent < step_count; ++exponent) {
    baby_steps.try_emplace(value, exponent);
    value = multiply_mod(value, base, prime_modulus);
  }

  const std::uint64_t inverse_base =
      power_mod(base, prime_modulus - 2U, prime_modulus);
  const std::uint64_t giant_factor =
      power_mod(inverse_base, step_count, prime_modulus);
  const std::uint64_t block_count =
      group_size / step_count + (group_size % step_count == 0U ? 0U : 1U);

  std::uint64_t gamma = target;
  for (std::uint64_t block = 0U; block < block_count; ++block) {
    const auto found = baby_steps.find(gamma);
    if (found != baby_steps.end()) {
      const std::uint64_t candidate = block * step_count + found->second;
      if (candidate < group_size &&
          power_mod(base, candidate, prime_modulus) == target) {
        return candidate;
      }
    }
    gamma = multiply_mod(gamma, giant_factor, prime_modulus);
  }
  return std::nullopt;
}

}  // namespace algorithms::number_theory
